version: "3"

services:
  rss_service:
    container_name: rss_service
    build: .
    environment:
      KAFKA_BROKER_URL: broker:9092
      TOPIC_NAME: projetRSS
      BATCH_SIZE: 10

networks:
  default:
    external:
      name: kafka-network
