version: '3'

services:
  cassandradb:
    user: root
    container_name: cassandradb
    image: bootstrapcassandra
    build: .
    ports:
      - 7000:7000
      - 9042:9042

networks:
  default:
    external:
      name: cassandra-network
